spring.application.name=ratings-data-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/movie_ratings_db
spring.datasource.username=youssef
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379