spring.application.name=movie-catalog-service
server.port=8081
management.endpoints.web.exposure.include=hystrix.stream

grpc.client.trending-service.address=static://localhost:9090
grpc.client.trending-service.negotiation-type=plaintext